Revert "NRP-9 Trying to get rid of annoying message which spams the logs"
This reverts commit 6c4c77efc861cc422a1a5a601c4036b260f80b61.
This did not work very well. Got
NoMethodError: undefined method `web_console' for #<Rails::Application::Configuration:0x005654631168c8>
Did you mean?  console